### PR TITLE
Add formatting around scope names

### PR DESCRIPTION
**Pull request by ddspringle**
Added additional formatting to 'this', 'variables' and 'local' when discussing scopes

### CODE REVIEW

**Comment by cfvonner** [comment]
@ddspringle can you resolve the conflict?  It might be that the file was updated after you forked the repository.

**Comment by ddspringle** [comment]
@cfvonner Conflicts resolved. Sorry about that!

**Comment by cfvonner** [comment]
@ddspringle my apologies. I wasn't paying attention to the repository involved here. This repo should get closed as we moved the content for LearnCFinaWeek to a new permanent public repository: https://github.com/learn-cfinaweek/v2-content. This new permanent home is accessible from a link on the new LearnCF site.

Can you check if those same corrections need to be made there, and if so, make a pull request there?

**Comment by ddspringle** [comment]
@cfvonner Ah. Gotcha. Will do. Thanks!

**Pull request merged**
